services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"  
      - "15672:15672" 
    expose:
      - "5672"
      - "15672"
    environment:
      RABBITMQ_DEFAULT_USER: adaptor
      RABBITMQ_DEFAULT_PASS: WuJQdoKxLI5v6oN2RKci1dOJd
    volumes:
      - rabbitmq3:/var/lib/rabbitmq
  minio:
    image: docker.io/bitnami/minio:2022
    expose:
      - "9000"
      - "9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio3:/data'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=webhook
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - minio
    develop:
      watch:
        - action: sync 
          path: .
          target: /app
        - action: rebuild
          path: .

volumes:
  rabbitmq3: {}
  minio3: {}
